DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID1',
    userId  VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    `name`   VARCHAR(255),
    regNo    VARCHAR(255) NOT NULL
    PRIMARY KEY (id)
);
